apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mongodb-credentials
  namespace: default
spec:
  encryptedData:
    MONGODB_DB: {{ .Values.mongo.database }}
    MONGODB_HOST: {{ .Values.mongo.host }}
    MONGODB_PASSWORD: {{ .Values.mongo.password }}
    MONGODB_USERNAME: {{ .Values.mongo.username }}
  template:
    metadata:
      name: mongodb-credentials
      namespace: default