apiVersion: v1
kind: Secret
metadata:
  name: harbor-credentials
  namespace: imagepullsecret-patcher
type: kubernetes.io/dockerconfigjson
stringData:  
  .dockerconfigjson: |
    {
    "auths": {
      "harbor.localhost.com": {
        "auth": "YWRtaW46SGFyYm9yMTIzNDU="
        }
      }
    }