replicaCount: 1

appPort: 5000

image:
  registry: harbot.localhost.com/jhonthanlocal/restapi-flask
  tag: harbot.localhost.com/jhonthanlocal/restapi-flask

environmentVariables:
  - name: MONGODB_DB
    value: api
  - name: MONGODB_HOST
    value: mongodb
  - name: MONGODB_USERNAME
    value: api
  - name: MONGODB_PASSWORD
    value: api

livenessProbe: {}

readinessProbe: {}

ingress:
  enabled: false

mongo:
  auth:
    usernames:
      - api
    password: 
      - api
    databases: 
      - api